name: PR Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Badge deps
        run: npm install --global jest-coverage-badges

      - name: Lint
        run: yarn lint

      - name: Save Code Linting Report JSON
        run: yarn run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: "eslint_report.json"

      - name: Test with coverage
        run: yarn run cu-test

      - name: Generate Badge
        run: jest-coverage-badges output ".github/badges"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'docs(coverage) Add test coverage badge'
          add: '*.svg'

      - name: Build
        run: yarn build
